company/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.homepage, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('news/', views.news, name='news'),
    path('services/', views.service, name='service'),
    path('service/<slug:slug>/', views.service_detail, name='service_detail'),
    path('resources/', views.resource, name='resource'),
    path('resource/<slug:slug>/', views.resource_detail, name='resource_detail'),
    path('blog/<slug:slug>/', views.blog_detail, name='blog_detail'),
    path('send-email/', views.send_email, name='send_email'),
    path('donate/', views.donate, name="donate")
]

poimen/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('company.urls')),
    path('froala_editor/', include('froala_editor.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

company/models.py
from django.db import models
from froala_editor.fields import FroalaField
from django.utils.text import slugify
from unidecode import unidecode
from fontawesome_5.fields import IconField
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.core.mail import EmailMultiAlternatives


#Blog Model
class Blog_Categories(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True,blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(unidecode(self.name))
        super().save(*args, **kwargs)
    
    def count_categories(self):
        return Blog.objects.filter(type__name = self.name).count()
    
    def __str__(self) -> str:
        return self.name

class Blog(models.Model):
    title = models.CharField(max_length=200)
    image = models.URLField()
    content = FroalaField()
    slug = models.SlugField(max_length=300, unique=True,blank=True)
    type = models.ManyToManyField(Blog_Categories)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    subscription_status = models.BooleanField(default=False)

    class Meta:
      ordering = ['-created_at', '-updated_at']

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(unidecode(self.title))
        super().save(*args, **kwargs)

    def count_comment(self):
      return Blog_Comment.objects.filter(post__id = self.pk, status = True).count()
    
    def send_email(self):
     subscribers = Subscription.objects.values_list('email')
     emails = list(subscribers)
     all_email = [x for tup in emails for x in tup]

     def send_email_each(email):
       subject = self.title
       from_email = '@gmail.com'
       to_email = email
       text_content = '<!DOCTYPE html>'
       html_content = self.content
       msg = EmailMultiAlternatives(subject, text_content, from_email, [to_email])
       msg.attach_alternative(html_content, "text/html")
       msg.send()
       return True
     
     if(self.subscription_status == True):
       send_email_fun = map(send_email_each, all_email) 
     

    def __str__(self) -> str:
        return self.title

@receiver(pre_save, sender=Blog)
def call_my_function(sender, instance, **kwargs):
    instance.send_email()
    
class Blog_Comment(models.Model):
   name = models.CharField(max_length=200)
   email = models.EmailField()
   comment = models.TextField()
   website = models.URLField()
   post = models.ForeignKey(Blog, on_delete=models.CASCADE)
   status  = models.BooleanField(default=False)
   date = models.DateTimeField(auto_now=True)
   
   
   def __str__(self):
      return self.name
    
#Resource Model
class Resource(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    author_image = models.URLField()
    author_description = models.TextField(null=True, blank=True)
    title = models.CharField(max_length=200)
    icon = IconField()
    image = models.URLField()
    short_description = models.CharField(max_length=200)
    document_link = models.URLField(max_length=200)
    content = FroalaField()
    subscription_status = models.BooleanField(default=False)
    slug = models.SlugField(max_length=300, unique=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
      ordering = ['-created_at', '-updated_at']

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(unidecode(self.title))
        super().save(*args, **kwargs)

    def count_comment(self):
      return Resource_Comment.objects.filter(post__id = self.pk, status = True).count()

    def __str__(self) -> str:
        return self.title
    def send_email(self):
     subscribers = Subscription.objects.values_list('email')
     emails = list(subscribers)
     all_email = [x for tup in emails for x in tup]

     def send_email_each(email):
       subject = self.title
       from_email = '@gmail.com'
       to_email = email
       text_content = '<!DOCTYPE html>'
       html_content = self.content
       msg = EmailMultiAlternatives(subject, text_content, from_email, [to_email])
       msg.attach_alternative(html_content, "text/html")
       msg.send()
       return True
     
     if(self.subscription_status == True):
       send_email_fun = map(send_email_each, all_email) 
     
    def __str__(self) -> str:
        return self.title


@receiver(pre_save, sender=Resource)
def call_my_function(sender, instance, **kwargs):
    instance.send_email()


class Resource_Comment(models.Model):
   name = models.CharField(max_length=200)
   email = models.EmailField()
   comment = models.TextField()
   website = models.URLField(blank=True, null=True)
   post = models.ForeignKey(Resource, on_delete=models.SET_NULL, null=True)
   status  = models.BooleanField(default=True)
   date = models.DateTimeField(auto_now=True)
   
   
   def __str__(self):
      return self.name
    
#Service 
class Service(models.Model):
    icon = IconField()
    image = models.URLField()
    title = models.CharField(max_length=50)
    short_description = models.CharField(max_length=300)
    content = FroalaField()
    slug = models.SlugField(max_length=300, unique=True,blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(unidecode(self.title))
        super().save(*args, **kwargs)


    def __str__(self) -> str:
        return self.title
    
#Gallery 
class Gallery_Categories(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.name
    
class Gallery(models.Model):
    title = models.CharField(max_length=100)
    category = models.ForeignKey(Gallery_Categories,on_delete=models.CASCADE, null=True)
    image = models.URLField()
    slug = models.SlugField(max_length=100, unique=True,blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(unidecode(self.title))
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return self.title


#Subscription 
class Subscription(models.Model):
    name = models.CharField(max_length=40)
    email = models.EmailField()
    message = models.TextField(blank=True, null=True)

    def __str__(self) -> str:
        return self.name

company/forms.py
from django import forms
from . import models

class ResourceComment(forms.ModelForm):
    name = forms.CharField(max_length=100, required=True, error_messages={'required': 'Title can not be empty'})
    email = forms.EmailField(required=True, error_messages={'required': 'Email can not be empty'})
    website =forms.URLField(required=False)
    comment = forms.CharField( required=True, widget=forms.TextInput())

    class Meta:
        model = models.Resource_Comment
        fields = ("name","email", "website", "comment")

class BlogComment(forms.ModelForm):
    name = forms.CharField(max_length=100, required=True, error_messages={'required': 'Title can not be empty'})
    email = forms.EmailField(required=True, error_messages={'required': 'Email can not be empty'})
    website =forms.URLField(required=False)
    comment = forms.CharField( required=True, widget=forms.TextInput())

    class Meta:
        model = models.Blog_Comment
        fields = ("name","email", "website", "comment")

class SubscriptionForm(forms.ModelForm):
    name = forms.CharField(max_length=100, required=True, error_messages={'required': 'Title can not be empty'})
    email = forms.EmailField(required=True, error_messages={'required': 'Email can not be empty'})
    message = forms.CharField(widget=forms.Textarea())

    class Meta:
        model = models.Subscription
        fields = '__all__'
    

company/views.py
from django.shortcuts import render
from . import models
from . import forms
from django.core.paginator import Paginator
from django.core.mail import send_mail
# Create your views here.
def homepage(request):
    recent_blog = models.Blog.objects.all()[:3]
    resource = models.Resource.objects.all()[:6]

    if request.method == 'POST':
        form = forms.SubscriptionForm(request.POST)
        if form.is_valid():
            form.save()
            form = forms.SubscriptionForm()
    else:
        form = forms.SubscriptionForm()

    
    context = {
        'recent_blog' : recent_blog,
        'resources' : resource
    }
    return render(request, 'company/index.html', context)

def about(request):
    return render(request, 'company/about.html')

def donate(request):
    return render(request, 'company/donate.html')
def contact(request):
     return render(request, 'company/contact.html')

def news(request):

    blogs = models.Blog.objects.all()
    paginator = Paginator(blogs, 6)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {
        'page' : page,
        'blogs' : blogs,
        'categories' : models.Blog_Categories.objects.all(),
    }
   
    
    return render(request, 'company/news.html', context)


def service(request):

    services = models.Service.objects.all()

    context = {
        'services' : services,
    }
    return render(request, 'company/services.html', context)

def service_detail(request, slug):
    service_detail = models.Service.objects.filter(slug = slug).first()

    context = {
        'service' : service_detail
    }
    return render(request, 'company/service-details.html', context)

def resource(request):
    resources = models.Resource.objects.all()
    paginator = Paginator(resources, 6)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)

    context = {
        'page' : page,
    }
    return render(request, 'company/resource.html', context)

def resource_detail(request, slug):
    resource_detail = models.Resource.objects.get(slug = slug)
    comment = models.Resource_Comment.objects.filter(post__pk = resource_detail.pk, status = True)
    
    form = forms.ResourceComment()
    context = {
        'resource' : resource_detail,
        'comment' : comment,
        'form' : form
    }
    if request.method == 'POST':
        form = forms.ResourceComment(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = resource_detail
            comment.save()
            return render(request, 'company/resource-details.html', context)

    return render(request, 'company/resource-details.html', context)



def blog_detail(request, slug):

    blog_detail = models.Blog.objects.filter(slug = slug).first()
    recent_blogs = models.Blog.objects.all()[:5]
    comment = models.Blog_Comment.objects.filter(status = True, post__id = blog_detail.id)

    form = forms.BlogComment()

    context = {
        'blog' : blog_detail,
        'categories' : models.Blog_Categories.objects.all(),
        'recent_blogs' : recent_blogs,
        'comments' : comment,
        'form' : form
    }
    if request.method == 'POST':
        form = forms.BlogComment(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = blog_detail
            comment.save()
            form = forms.BlogComment()     
            return render(request, 'company/blog-details.html', context)
    
    return render(request, 'company/blog-details.html', context)

def send_email(request):
    if request.method == 'POST':
        name = request.POST.get('name', '')
        email = request.POST.get('email', '')
        subject = request.POST.get('subject', '')
        message = request.POST.get('message', '')

        # Send the email
        send_mail(
            subject,
            f"Name: {name}\nEmail: {email}\n\n{message}",
            email,
            ['nahomkebede91@gmail.com'],
            fail_silently=True,
        )

        # Return a JSON response to indicate success
        return JsonResponse({'success': True})

    # Return a JSON response to indicate an error
    return JsonResponse({'success': True})

company/templates/company/blog-details.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />

    <title>Poimen - Blog Details</title>
    <meta content="" name="description" />
    <meta content="" name="keywords" />

    {% include 'company/include/head.html'%}
  </head>

  <body>
    {% include 'company/include/navbar.html'%}
    <main id="main">
      <!-- ======= Breadcrumbs ======= -->
      <div
        class="breadcrumbs d-flex align-items-center"
        style="
          background-image: url('{% static 'assets/img/breadcrumbs-bg.jpg' %}');
        "
      >
        <div
          class="container position-relative d-flex flex-column align-items-center"
          data-aos="fade"
        >
          <h2>News Details</h2>
          <ol>
            <li><a href="{% url 'index' %}">Home</a></li>
            <li>News Details</li>
          </ol>
        </div>
      </div>
      <!-- End Breadcrumbs -->

      <!-- ======= Blog Details Section ======= -->
      <section id="blog" class="blog">
        <div class="container" data-aos="fade-up" data-aos-delay="100">
          <div class="row g-5">
            <div class="col-lg-8">
              <article class="blog-details">
                <div class="post-img">
                  <img src="/media/{{blog.image}}" alt="" class="img-fluid" />
                </div>

                <h2 class="title">{{blog.title}}</h2>

                <div class="meta-top">
                  <ul>
                    <!-- <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a href="blog-details.html">John Doe</a></li> -->
                    <li class="d-flex align-items-center">
                      <i class="bi bi-clock"></i>
                      <a href="blog-details.html"
                        >{{blog.created_at |timesince }}</a
                      >
                    </li>
                    <li class="d-flex align-items-center">
                      <i class="bi bi-chat-dots"></i>
                      <a href="blog-details.html"
                        >{{blog.count_comment}} Comments</a
                      >
                    </li>
                  </ul>
                </div>
                <!-- End meta top -->

                <div class="content">{{blog.content | safe}}</div>
                <!-- End post content -->
              </article>
              <!-- End blog post -->

              <div class="post-author d-flex align-items-center">
                <!-- <img
                  src="{% static 'assets/img/blog/' %}"
                  class="rounded-circle flex-shrink-0"
                  alt=""
                /> -->
                <!-- <div>
                  <h4></h4>
                  <div class="social-links">
                    <a href="https://twitters.com/#"
                      ><i class="bi bi-twitter"></i
                    ></a>
                    <a href="https://facebook.com/#"
                      ><i class="bi bi-facebook"></i
                    ></a>
                    <a href="https://instagram.com/#"
                      ><i class="biu bi-instagram"></i
                    ></a>
                  </div>
                  <p>
                    
                  </p>
                </div> -->
              </div>
              <!-- End post author -->

              <div class="comments">
                <!-- <h4 class="comments-count">{{blog.count_comment}} Comments</h4> -->

                {% for comment in comments %}
                <div id="comment-1" class="comment">
                  <div class="d-flex">
                    <div class="comment-img">
                      <img
                        src="{% static 'assets/img/blog/comments-1.png' %}"
                        alt=""
                      />
                    </div>
                    <div>
                      <h5>
                        <a href="">{{comment.name}}</a>
                      </h5>
                      <time datetime="2020-01-01"
                        >{{comment.date | date:'F d, Y'}}</time
                      >
                      <p>{{comment.comment}}</p>
                    </div>
                  </div>
                </div>
                <!-- End comment #1 -->
                {% endfor %}

                <div class="reply-form">
                  <h4>Leave a Reply</h4>
                  <p>
                    Your email address will not be published. Required fields
                    are marked *
                  </p>
                  <form action="" method="post">
                    {% csrf_token %}          
                    <div class="row">
                      <div class="col-md-6 form-group">
                        <input
                          name="name"
                          type="text"
                          class="form-control {% if form.name.errors %} is-invalid {% endif %} "
                          placeholder="Your Name*"
                          id="id_name"
                        />
                      </div>
                      <div class="col-md-6 form-group">
                        <input
                          name="email"
                          type="text"
                          class="form-control{% if form.email.errors %} is-invalid {% endif %} "
                          placeholder="Your Email*"
                          id="id_email"
                        />
                      </div>
                    </div>

                    <div class="row">
                      <div class="col form-group">
                        <input
                          name="website"
                          type="text"
                          class="form-control {% if form.website.errors %} is-invalid {% endif %} "
                          placeholder="Your Website"
                          id="id_website"
                        />
                      </div>
                    </div>
                    <div class="row">
                      <div class="col form-group">
                        <textarea
                          name="comment"
                          class="form-control {% if form.comment.errors %} is-invalid {% endif %} "
                          placeholder="Your Comment*"
                          id="id_comment"
                        ></textarea>
                      </div>
                    </div>
                    <button type="submit" class="btn btn-primary">
                      Post Comment
                    </button>
                  </form>

                </div>
              </div>
              <!-- End blog comments -->
            </div>

            <div class="col-lg-4">
              <div class="sidebar">
                <!-- End sidebar search formn-->

                <div class="sidebar-item categories">
                  <h3 class="sidebar-title">Categories</h3>
                  <ul class="mt-3">
                    {% for category in categories%}
                    <li>
                      <a href="#"
                        >{{category}}
                        <span>({{category.count_categories}})</span></a
                      >
                    </li>
                    {% endfor %}
                  </ul>
                </div>
                <!-- End sidebar categories-->

                <div class="sidebar-item recent-posts">
                  <h3 class="sidebar-title">Recent Posts</h3>

                  <div class="mt-3">
                    {% for recent_blog in recent_blogs %}
                    <div class="post-item mt-3">
                      <img src="/media/{{recent_blog.image}}" alt="" />
                      <div>
                        <h4>
                          <a href="{% url 'blog_detail' recent_blog.slug %}"
                            >{{recent_blog.title}}</a
                          >
                        </h4>
                        <time datetime="2020-01-01"
                          >{{recent_blog.created_at | date:'F d, Y'}}</time
                        >
                      </div>
                    </div>
                    <!-- End recent post item-->
                    {% endfor %}
                  </div>
                </div>
                <!-- End sidebar recent posts-->

                <!-- End sidebar tags-->
              </div>
              <!-- End Blog Sidebar -->
            </div>
          </div>
        </div>
      </section>
      <!-- End Blog Details Section -->
    </main>
    <!-- End #main -->

    {% include 'company/include/footer.html'%}

    <a
      href="#"
      class="scroll-top d-flex align-items-center justify-content-center"
      ><i class="bi bi-arrow-up-short"></i
    ></a>

    <div id="preloader"></div>
    {% include 'company/include/vendor.html'%}
  </body>
</html>

company/templates/company/resource-details.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />

    <title>Poimen - Resource Details</title>
    <meta content="" name="description" />
    <meta content="" name="keywords" />

    {% include 'company/include/head.html'%}
  </head>

  <body>
    {% include 'company/include/navbar.html'%}
    <main id="main">
      <!-- ======= Breadcrumbs ======= -->
      <div
        class="breadcrumbs d-flex align-items-center"
        style="
          background-image: url('{% static 'assets/img/breadcrumbs-bg.jpg' %}');
        "
      >
        <div
          class="container position-relative d-flex flex-column align-items-center"
          data-aos="fade"
        >
          <h2>Resource Details</h2>
          <ol>
            <li><a href="{% url 'resource'%}">Resource</a></li>
            <li>Resource Details</li>
          </ol>
        </div>
      </div>
      <!-- End Breadcrumbs -->

      <!-- ======= resouce detail Section ======= -->
      <section id="blog" class="blog">
        <div class="container" data-aos="fade-up" data-aos-delay="100">
          <div class="row g-5">
            <div class="col-lg-10">
              <article class="blog-details">
                <div class="post-img">
                  <img src="{{resource.image}}" alt="" class="img-fluid" />
                </div>

                <!-- start meta top-->
                <h2 class="title text-center">{{resource.title}}</h2>

                <div class="meta-top">
                  <ul>
                    <!-- <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a href="blog-details.html">John Doe</a></li> -->
                    <li class="d-flex align-items-end">
                      <i class="bi bi-clock"></i>
                      <a href="blog-details.html"
                        >{{resource.created_at |timesince }}</a
                      >
                    </li>
                    <li class="d-flex align-items-center">
                      <i class="bi bi-chat-dots"></i>
                      <a href="blog-details.html"
                        >{{resource.count_comment}} Comments</a
                      >
                    </li>
                  </ul>
                </div>
                <!-- End meta top -->

                <!--start the content-->
                <div class="content">
                  {{resource.content | safe}}
                  <a
                    href="{{resource.document_link}}"
                    class="readmore float-end"
                  >
                    <button class="btn btn-outline-primary">
                      Download <i class="bi bi-arrow-down"></i></button
                  ></a>
                  <br />
                </div>

                <!-- End post content -->
              </article>

              <!--author start here -->
              <div class="post-author d-flex align-items-center">
                <img
                  src="{{resource.author_image}}"
                  class="rounded-circle flex-shrink-0"
                  alt=""
                  style="width: 60px; height: 60px"
                />
                <div>
                  <h4>{{resource.user}}</h4>

                  <p>{{resource.author_description}}</p>
                </div>
              </div>
              <!-- End post author -->

              <!--this is a comments (but not working)-->
              <div class="comments">
                <h4 class="comments-count">
                  {{resource.count_comment}} Comments
                </h4>

                {% for cm in comment %}
                <div id="comment-1" class="comment">
                  <div class="d-flex">
                    <div class="comment-img">
                      <img
                        src="{% static 'assets/img/blog/comments-1.png' %}"
                        alt=""
                      />
                    </div>
                    <div>
                      <h5>
                        <a href="">{{cm.name}}</a>
                        <!-- <a href="#" class="reply"
                          ><i class="bi bi-reply-fill"></i> Reply</a
                        > -->
                      </h5>
                      <time datetime="2020-01-01"
                        >{{cm.date | date:'F d, Y'}}</time
                      >
                      <p>{{cm.comment}}</p>
                    </div>
                  </div>
                </div>
                <!-- End comment #1 -->
                {% endfor %}
                <!--comment forms-->
                <div class="reply-form">
                  <h4>Leave a Reply</h4>
                  <p>
                    Your email address will not be published. Required fields
                    are marked *
                  </p>
                  <form action="" method="post">
                    {% csrf_token %}
                    <div class="row">
                      <div class="col-md-6 form-group">
                        <input
                          name="name"
                          type="text"
                          class="form-control {% if form.name.errors %} is-invalid {% endif %}"
                          placeholder="Your Name*"
                          id="id_name"
                        />
                      </div>
                      <div class="col-md-6 form-group">
                        <input
                          name="email"
                          type="text"
                          class="form-control{% if form.email.errors %} is-invalid {% endif %}"
                          placeholder="Your Email*"
                          id="id_email"
                        />
                      </div>
                    </div>

                    <div class="row">
                      <div class="col form-group">
                        <input
                          name="website"
                          type="text"
                          class="form-control {% if form.website.errors %} is-invalid {% endif %}"
                          placeholder="Your Website"
                          id="id_website"
                        />
                      </div>
                    </div>
                    <div class="row">
                      <div class="col form-group">
                        <textarea
                          name="comment"
                          class="form-control {% if form.comment.errors %} is-invalid {% endif %}"
                          placeholder="Your Comment*"
                          id="id_comment"
                        ></textarea>
                      </div>
                    </div>
                    <button type="submit" class="btn btn-primary">
                      Post Comment
                    </button>
                  </form>
                </div>
              </div>
              <!-- End comment forms -->
            </div>
          </div>
        </div>
      </section>
      <!-- End resource detail Section -->
    </main>
    <!-- End #main -->

    {% include 'company/include/footer.html'%}

    <a
      href="#"
      class="scroll-top d-flex align-items-center justify-content-center"
      ><i class="bi bi-arrow-up-short"></i
    ></a>

    <div id="preloader"></div>
    {% include 'company/include/vendor.html'%}
  </body>
</html>

company/templates/company/service-details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Poimen - Service Details</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

{% include 'company/include/head.html' %}
</head>

<body>

   {% include 'company/include/navbar.html'%}
  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs d-flex align-items-center" style="background-image: url('{% static 'assets/img/breadcrumbs-bg.jpg' %}');">
      <div class="container position-relative d-flex flex-column align-items-center" data-aos="fade">

        <h2>Service Details</h2>
        <ol>
          <li><a href="{% url 'service' %}">Service</a></li>
          <li>Service Details</li>
        </ol>

      </div>
    </div><!-- End Breadcrumbs -->

    <!-- ======= Service Details Section ======= -->
    <section id="service-details" class="service-details">
      <div class="container" data-aos="fade-up" data-aos-delay="100">

        <div class="row gy-4">

          <div class="col-12 col-md-12">
            <img width = "400px" height = "350px" src="{{service.image}}" alt="" class="img-fluid " >
    
            <h3 class="text-info my-2">{{service.title}}</h3>
            <p class="shadow-lg border"> {{service.content | safe }}</p>
           
        </div>

      </div>
    </section><!-- End Service Details Section -->

  </main><!-- End #main -->
  {% include 'company/include/footer.html'%}

  <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <div id="preloader"></div>
{% include 'company/include/vendor.html'%}
</body>

</html>